/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_glitter_ndktest_JNIUtils */

#ifndef _Included_com_glitter_ndktest_JNIUtils
#define _Included_com_glitter_ndktest_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_glitter_ndktest_JNIUtils
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_glitter_ndktest_JNIUtils_sayHello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
